import { useState } from "react";
import { useNavigate } from "react-router-dom";
import PageContainer from "../../components/layout/PageContainer";
import SectionHeading from "../../components/common/SectionHeading";
import Card from "../../components/common/Card";
import Button from "../../components/common/Button";
import Input from "../../components/common/Input";
import Select from "../../components/common/Select";
import { useData } from "../../context/DataContext";
import { useAuth } from "../../context/AuthContext";
function CreateListing(){const {products,addMarketplaceListing,getProductHealth}=useData();const {user}=useAuth();const navigate=useNavigate();const owned=products.filter(p=>p.ownerId===user?.id);const [productId,setProductId]=useState(owned[0]?.id||"");const [price,setPrice]=useState("");const [location,setLocation]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);async function submit(e){e.preventDefault();const p=owned.find(x=>x.id===productId);if(!p||!price||!location)return setError("Select a product and complete the listing details.");setLoading(true);try{const {score}=getProductHealth(p);await addMarketplaceListing({productId,price:Number(price),location,health:score,imageUrl:p.imageUrl||""});navigate('/customer/listings');}catch(err){setError(err.message);}finally{setLoading(false);}}return <PageContainer className="space-y-6 py-8"><SectionHeading eyebrow="Marketplace" title="Create a Listing" description="Submit a registered product for marketplace review. The product photo and health score are carried into the listing."/><Card className="max-w-2xl"><form onSubmit={submit} className="space-y-4">{error&&<p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{owned.length===0?<div className="rounded-2xl bg-reloop-neutral p-5"><p className="text-sm font-semibold">No registered products yet.</p><p className="mt-1 text-xs text-reloop-espresso/50">Register a product first, including its image, then return here to list it.</p></div>:<><Select id="product" label="Product" value={productId} onChange={e=>setProductId(e.target.value)} options={owned.map(p=>({value:p.id,label:`${p.name} · ${p.condition}`}))}/><Input id="price" label="Asking price (PKR)" type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} placeholder="165000"/><Input id="location" label="Location" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Lahore"/><Button type="submit" loading={loading} className="w-full">Submit for review</Button></>}</form></Card></PageContainer>}
export default CreateListing;
