import { useState } from "react";
import { Recycle } from "lucide-react";
import PageContainer from "../../components/layout/PageContainer";
import SectionHeading from "../../components/common/SectionHeading";
import Card from "../../components/common/Card";
import Button from "../../components/common/Button";
import { useData } from "../../context/DataContext";
import { useAuth } from "../../context/AuthContext";
function Recycling(){const {products,recycling,addRecycling}=useData();const {user}=useAuth();const owned=products.filter(p=>p.ownerId===user?.id);const [loading,setLoading]=useState("");async function start(product){setLoading(product.id);try{await addRecycling({productId:product.id,center:"ReLoop Recovery Network"});}catch(err){alert(err.message);}finally{setLoading("");}}return <PageContainer className="space-y-6 py-8"><SectionHeading eyebrow="Recycling" title="Responsible end of life" description="Prepare products that are no longer practical to repair for responsible recovery."/><Card><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-reloop-chartreuse/30"><Recycle size={19}/></div><div><h3 className="font-display text-lg font-bold">Choose a product</h3><p className="text-xs text-reloop-espresso/45">A recycling request is stored in MongoDB and tracked from your dashboard.</p></div></div><div className="mt-6 space-y-3">{owned.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-2xl border border-reloop-espresso/8 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">{p.name}</p><p className="text-xs text-reloop-espresso/45">{p.condition} · {p.lifecycleStatus}</p></div><Button variant="outline" loading={loading===p.id} onClick={()=>start(p)}>Prepare for recycling</Button></div>)}{owned.length===0&&<p className="text-sm text-reloop-espresso/50">Register a product before starting recycling.</p>}</div></Card>{recycling.length>0&&<Card><h3 className="font-display text-lg font-bold">Recycling requests</h3><div className="mt-4 space-y-3">{recycling.map(r=><div key={r._id} className="flex items-center justify-between rounded-xl border border-reloop-espresso/8 p-4 text-sm"><span>{r.productId?.name||'Product'}</span><span className="rounded-full bg-reloop-chartreuse px-3 py-1 text-xs font-semibold">{r.status}</span></div>)}</div></Card>}</PageContainer>}
export default Recycling;
