import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { AlertCircle, UserPlus } from "lucide-react";
import Input from "../../components/common/Input";
import Button from "../../components/common/Button";
import { useAuth } from "../../context/AuthContext";
import { cn } from "../../utils/cn";
const roleHome={customer:"/customer/dashboard",repair_partner:"/partner/dashboard"};
const roleOptions=[{value:"customer",title:"Customer",description:"Register products and manage their lifecycle."},{value:"repair_partner",title:"Repair Partner",description:"Receive repair jobs from ReLoop customers."}];
function Register(){const {register,verifyEmail}=useAuth();const navigate=useNavigate();const [form,setForm]=useState({name:"",email:"",password:"",confirmPassword:"",role:"customer",businessName:"",location:""});const [errors,setErrors]=useState({});const [formError,setFormError]=useState("");const [loading,setLoading]=useState(false);const [verification,setVerification]=useState(false);const [code,setCode]=useState("");
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 function validate(){const n={};if(!form.name.trim())n.name="Name is required.";if(!form.email.trim())n.email="Email is required.";if(form.password.length<6)n.password="Password must be at least 6 characters.";if(form.password!==form.confirmPassword)n.confirmPassword="Passwords do not match.";if(form.role==='repair_partner'&&!form.businessName.trim())n.businessName="Business name is required.";setErrors(n);return !Object.keys(n).length;}
 async function submit(e){e.preventDefault();if(!validate())return;setLoading(true);setFormError("");try{await register(form);setVerification(true);}catch(err){setFormError(err.message);}finally{setLoading(false);}}
 async function verify(e){e.preventDefault();setLoading(true);try{const data=await verifyEmail({email:form.email,code});navigate(roleHome[data.user.role],{replace:true});}catch(err){setFormError(err.message);}finally{setLoading(false);}}
 return <main className="flex min-h-screen items-center justify-center bg-reloop-ivory px-4 py-16"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="w-full max-w-lg rounded-3xl border border-reloop-espresso/10 bg-white p-8 shadow-[0_20px_60px_rgba(33,26,23,0.06)]"><div className="mb-8 text-center"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-reloop-orange font-display font-bold text-white">R</span><h1 className="mt-4 font-display text-2xl font-bold">{verification?"Verify your email":"Create your ReLoop account"}</h1><p className="mt-2 text-sm text-reloop-espresso/55">{verification?`A 6-digit code was sent to ${form.email}.`:"Start managing your product lifecycle today."}</p></div>{formError&&<div className="mb-5 flex items-start gap-2 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><AlertCircle size={16}/>{formError}</div>}{verification?<form onSubmit={verify} className="space-y-4"><Input id="verifyCode" label="Email verification code" value={code} onChange={e=>setCode(e.target.value)} placeholder="123456"/><Button type="submit" className="w-full" loading={loading}>Verify account</Button></form>:<><div className="mb-6 grid grid-cols-2 gap-3">{roleOptions.map(o=><button key={o.value} type="button" onClick={()=>setForm({...form,role:o.value})} className={cn("rounded-2xl border p-4 text-left",form.role===o.value?"border-reloop-orange bg-reloop-orange/5":"border-reloop-espresso/12") }><p className="font-display text-sm font-bold">{o.title}</p><p className="mt-1 text-xs leading-5 text-reloop-espresso/50">{o.description}</p></button>)}</div><form onSubmit={submit} className="space-y-4"><Input id="name" name="name" label="Full name" value={form.name} onChange={change} error={errors.name}/>{form.role==='repair_partner'&&<div className="grid gap-4 sm:grid-cols-2"><Input id="businessName" name="businessName" label="Business name" value={form.businessName} onChange={change} error={errors.businessName}/><Input id="location" name="location" label="Location" value={form.location} onChange={change}/></div>}<Input id="email" name="email" type="email" label="Email" value={form.email} onChange={change} error={errors.email}/><div className="grid grid-cols-2 gap-4"><Input id="password" name="password" type="password" label="Password" value={form.password} onChange={change} error={errors.password}/><Input id="confirmPassword" name="confirmPassword" type="password" label="Confirm password" value={form.confirmPassword} onChange={change} error={errors.confirmPassword}/></div><Button type="submit" className="w-full" loading={loading}><UserPlus size={16}/> Create account</Button></form></>}<p className="mt-6 text-center text-sm text-reloop-espresso/55">Already have an account? <Link to="/login" className="font-semibold text-reloop-orange">Sign in</Link></p></motion.div></main>}
export default Register;
