import { Router } from "express";
import User from "../models/User.js";
import Listing from "../models/Listing.js";
import Product from "../models/Product.js";
import RepairRequest from "../models/RepairRequest.js";
import Donation from "../models/Donation.js";
import Recycling from "../models/Recycling.js";
import Settings from "../models/Settings.js";
import Notification from "../models/Notification.js";
import { auth, requireRole } from "../middleware/auth.js";
const router=Router(); router.use(auth,requireRole('admin'));
router.get('/marketplace',async(req,res)=>res.json(await Listing.find().sort({createdAt:-1})));
router.get('/users',async(req,res)=>res.json(await User.find().sort({createdAt:-1}).select('-password -verificationCode -resetCode')));
router.patch('/users/:id',async(req,res)=>{const u=await User.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true}).select('-password -verificationCode -resetCode');if(!u)return res.status(404).json({message:'User not found.'});res.json(u);});
router.get('/providers',async(req,res)=>{const rows=await User.find({role:'repair_partner'}).sort({createdAt:-1}).select('-password -verificationCode -resetCode');res.json(rows);});
router.patch('/providers/:id',async(req,res)=>{const u=await User.findOneAndUpdate({_id:req.params.id,role:'repair_partner'},req.body,{new:true,runValidators:true}).select('-password -verificationCode -resetCode');if(!u)return res.status(404).json({message:'Provider not found.'});res.json(u);});
router.get('/dashboard',async(req,res)=>{const [users,products,repairs,listings,providers,pending,donations,recycling]=await Promise.all([User.countDocuments(),Product.countDocuments(),RepairRequest.countDocuments(),Listing.countDocuments({status:{$ne:'Removed'}}),User.countDocuments({role:'repair_partner'}),User.countDocuments({role:'repair_partner',verificationStatus:'Pending'}),Donation.countDocuments(),Recycling.countDocuments()]);const lifecycle=await Product.aggregate([{$group:{_id:'$lifecycleStatus',value:{$sum:1}}}]);const repair=await RepairRequest.aggregate([{$group:{_id:'$status',value:{$sum:1}}}]);res.json({metrics:{users,products,repairs,listings,providers,pending,donations,recycling},lifecycleData:lifecycle.map(x=>({name:x._id,value:x.value})),repairData:repair.map(x=>({name:x._id,value:x.value}))});});
router.get('/analytics',async(req,res)=>{const [users,products,repairs,listings,providers,donations,recycling]=await Promise.all([User.countDocuments(),Product.countDocuments(),RepairRequest.countDocuments(),Listing.countDocuments({status:'Active'}),User.countDocuments({role:'repair_partner',verificationStatus:'Verified'}),Donation.countDocuments(),Recycling.countDocuments()]);const repairData=await RepairRequest.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]);res.json({metrics:{users,products,repairs,listings,providers,donations,recycling},repairData:repairData.map(x=>({status:x._id,count:x.count}))});});
router.get('/settings',async(req,res)=>{res.json(await Settings.findOneAndUpdate({key:'platform'},{$setOnInsert:{key:'platform'}},{new:true,upsert:true}));});
router.patch('/settings',async(req,res)=>{res.json(await Settings.findOneAndUpdate({key:'platform'},req.body,{new:true,upsert:true,runValidators:true}));});
router.get('/donations',async(req,res)=>res.json(await Donation.find().populate('productId','name').sort({createdAt:-1}))); router.patch('/donations/:id',async(req,res)=>res.json(await Donation.findByIdAndUpdate(req.params.id,req.body,{new:true})));
router.get('/recycling',async(req,res)=>res.json(await Recycling.find().populate('productId','name').sort({createdAt:-1}))); router.patch('/recycling/:id',async(req,res)=>res.json(await Recycling.findByIdAndUpdate(req.params.id,req.body,{new:true})));
export default router;
